---
name: workflow to run linux commands 
on: workflow_dispatch
jobs:
  job1:
      runs-on: ubuntu-latest
      steps:
      - name: run linux command
        run: pwd
  job2:
      runs-on: ubuntu-22.04
      steps:
      - name: run multiple linux commands
        run: |
        hostname -s 
        echo "Welcome to github ations tutorial"
